In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [4]:
arr = np.array(mylist)

In [5]:
# matrixes as nested lists basically
mylist = [[1,2,3],[2,3,4],[5,6,7]]
mymat = np.array(mylist)

In [6]:
mymat.shape

(3, 3)

In [7]:
# start inclusive end is not lst 
# start, stop, step
np.arange(0,10)
np.arange(0,11,3)

array([0, 3, 6, 9])

In [8]:
np.zeros(4) #floating point numbers

array([0., 0., 0., 0.])

In [9]:
# can pass in tuple
np.zeros((4,10))


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
# can add to stuff 
np.ones((5,10)) + 4

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [12]:
# or other math
(np.ones((5,10)) +1)  * 7

array([[14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.]])

In [13]:
# start, stop, number of items.
# returns even spaced numbers
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

## Part 2

In [14]:
# rand # between 0 and 1 
print(
    np.random.rand(1),
    '\n\n',
    np.random.rand(4),
    '\n\n',
    np.random.rand(5,5)
)

[0.85754543] 

 [0.89566445 0.08663076 0.36644139 0.72931542] 

 [[0.61405647 0.68029205 0.20863032 0.45914331 0.52643749]
 [0.14599334 0.27705303 0.26264763 0.11534545 0.90540538]
 [0.2302165  0.01251247 0.95329554 0.9295814  0.69782688]
 [0.7055793  0.35205634 0.78850945 0.27453545 0.55305305]
 [0.873063   0.92069556 0.50466548 0.37051475 0.67442259]]


In [15]:
# randint
#low, high, number of items to return
np.random.randint(55)

1

In [16]:
# get the same random numbers
# must be in same cell.
np.random.seed(42)
np.random.rand(4)


array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [17]:
# max min, argmax, argmin
# argmax and argmin return the index location of the min/max respectably
ranarr = np.random.randint(0,100, 10)
print(
    ranarr,
    '\n\n',
    ranarr.max(),
    '\n\n',
    ranarr.min(),
    '\n\n',
    ranarr.argmin(),
    '\n\n',
    ranarr.argmax()
)

[82 86 74 74 87 99 23  2 21 52] 

 99 

 2 

 7 

 5


### Part 3

In [18]:
arr = np.arange(0,11)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr[8]

8

In [22]:
arr[1:7]

array([1, 2, 3, 4, 5, 6])

In [23]:
arr[:5]

array([0, 1, 2, 3, 4])

In [24]:
#broadcasting functions and opps
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [25]:
new_arr = arr /2

In [26]:
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [27]:
#slice still point to og arr

slice_of_arr = arr[0:6]

In [28]:
slice_of_arr[:] = 99

In [29]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [31]:
# need to be explicit if don't want save over
arr_copy = arr.copy()

In [32]:
arr_copy[:] = 1000000000000

In [33]:
arr_copy

array([-727379968, -727379968, -727379968, -727379968, -727379968,
       -727379968, -727379968, -727379968, -727379968, -727379968,
       -727379968])

In [35]:
arr #unmodified

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
# indexing matrix (aka 2d array)

In [40]:
# all needs to be contained in a list
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [41]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [42]:
arr_2d.shape

(3, 3)

In [43]:
# row then col
arr_2d[1,]

array([20, 25, 30])

In [46]:
arr_2d[2,2]

45

In [53]:
arr_2d[0:2,1:3]

array([[10, 15],
       [25, 30]])

In [54]:
# conditional selection
arr = np.arange(1,11)

In [55]:
arr >4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [56]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [58]:
# or if want to be more clear
filter = arr > 4
arr[filter]

array([ 5,  6,  7,  8,  9, 10])

### Part 4: Operations

In [59]:
# element by element and broadcast on array
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [61]:
arr / 100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [62]:
arr **2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [63]:
(arr + 2)/100

array([0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11, 0.12])

In [64]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [65]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [66]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [67]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [69]:
np.sum(arr)

55

In [71]:
np.mean(arr)

5.5

In [73]:
np.max(arr)

10

In [75]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])

In [77]:
np.sum(arr_2d) #sums up all numbers

78

In [78]:
arr_2d.sum(axis=0)
# GIVE SUM ACCROSS THE ROWS
# SUM OF COLS

array([15, 18, 21, 24])

In [80]:
arr_2d.sum(axis=1) # columns
#GIVE SUM ACCROSS COLUMNS
# SUM OF ROW VALS

array([10, 26, 42])