# Intro to Pytorch

#### imports

In [1]:
import torch
import numpy as np

## Tensor Basics Part 1

In [2]:
torch.__version__

'1.6.0'

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.dtype

dtype('int32')

In [7]:
type(arr)

numpy.ndarray

In [9]:
x = torch.from_numpy(arr)

In [10]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [11]:
type(x)

torch.Tensor

In [12]:
# alternate more generalized method
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [13]:
x.dtype

torch.int32

In [15]:
arr2d = np.arange(0.0,12.0)

In [17]:
arr2d = arr2d.reshape(4,3)

In [18]:
x2 = torch.from_numpy(arr2d)

In [19]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [20]:
# maintain original rel between x and arr

In [22]:
arr[0] = 99

In [24]:
# x has also been changed
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [34]:
# to do that unlinked can do it like this:

my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# this creates a copy
my_tensor = torch.tensor(my_arr)

# this is still attached (linked)
my_other_tensor = torch.from_numpy(my_arr)

my_arr[0] = 9999
print(my_tensor)
print(my_other_tensor)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)
tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       dtype=torch.int32)


## Tensor Basics Part 2

In [38]:
new_arr = np.array([1,2,3])

In [42]:
# lower vs capital t/T
print('CAPITAL = Int:')
print(torch.tensor(new_arr))
print('\n\nlower case = Float:')
print(torch.Tensor(new_arr))

CAPITAL = Int:
tensor([1, 2, 3], dtype=torch.int32)


lower case = Float:
tensor([1., 2., 3.])


In [43]:
# tensors from scratch
# first create placeholder to say how much memory to use
torch.empty(4,2)

tensor([[0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [1.8754e+28, 8.0439e+20]])

In [46]:
# also zeros 
# can choose data type
torch.zeros(4,3,dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [47]:
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [52]:
# can reshape
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [53]:
# can use linspace
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [54]:
# can pass in lists
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [56]:
# change data types
my_tensor = torch.tensor([1,2,3])
print(my_tensor.dtype)
my_tensor = my_tensor.type(torch.int32)
print(my_tensor.dtype)

torch.int64
torch.int32


In [57]:
# random numbers
#uniform dist 0 to 1
torch.rand(4,3)

tensor([[0.4254, 0.2224, 0.3605],
        [0.2664, 0.2720, 0.8895],
        [0.8749, 0.0848, 0.1345],
        [0.4971, 0.9702, 0.3646]])

In [59]:
# norm dist
torch.randn(4,3)

tensor([[ 0.1364,  1.0131, -0.9287],
        [-0.7116, -0.5470,  0.0252],
        [-0.5937, -0.1679,  0.8798],
        [-0.9256, -1.7518, -0.5297]])

In [62]:
# rand int low to high
# low is inclusize, high is not!
torch.randint(low=0,high=10,size=(5,5))

tensor([[4, 0, 1, 6, 3],
        [0, 5, 6, 7, 0],
        [7, 6, 8, 9, 7],
        [1, 7, 5, 6, 6],
        [9, 8, 8, 2, 4]])

In [64]:
x = torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [68]:
# takes shape from what you pass in to do 
print(torch.rand_like(x))
print()
print(torch.randn_like(x))
print()
print(torch.randint_like(x, low=0, high = 11))

tensor([[0.9886, 0.0015, 0.9355, 0.9588, 0.6648],
        [0.8059, 0.8756, 0.1408, 0.7723, 0.0832]])

tensor([[-0.5431,  0.7769,  2.2693, -0.8431, -2.3531],
        [-0.0730, -0.5131, -0.5374, -0.0404, -0.3722]])

tensor([[9., 7., 2., 5., 9.],
        [4., 8., 6., 6., 8.]])


In [70]:
# torch seed for random!
# these match teachers
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [71]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [72]:
torch.rand(2,3)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

## Tensor Operations Part 1

In [73]:
# indexing and slicing just like numpy

In [74]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [75]:
x[1,1]

tensor(3)

In [77]:
# grap every col from row 1
x[:1]

tensor([[0, 1]])

In [79]:
x[:,1]

tensor([1, 3, 5])

In [80]:
# if we want vertical columns request as slice
x[:,1:]


tensor([[1],
        [3],
        [5]])

In [81]:
# view vs reshape
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
# this isn't in place
x.view(2,5)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
# this also isn't in place?
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [88]:
# views reflect most current
x = torch.arange(10)
x.shape

torch.Size([10])

In [89]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [90]:
z = x.view(2,5)

In [92]:
x[0] = 9999

In [93]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [94]:
x = torch.arange(10)
x.shape

torch.Size([10])

In [95]:
# -1 pytorch infers what the max is
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [96]:
# Arithmatic

In [100]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])

In [101]:
a

tensor([1., 2., 3.])

In [102]:
b

tensor([4., 5., 6.])

In [103]:
# element by element
a + b

tensor([5., 7., 9.])

In [105]:
# could also do
torch.add(a,b)

tensor([5., 7., 9.])

In [108]:
# change tensor in place
# could either do 
# a = a * b
# or with underscore methods
print(a.mul_(b))
print(a)

tensor([ 16.,  50., 108.])


tensor([ 16.,  50., 108.])

## Tensor Operations Part 2

In [109]:
# reset values
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])

In [110]:
# dot product
a.dot(b)

tensor(32.)

In [114]:
# matrix mult (dimensions must line up)
a = torch.tensor([[0,2,4], [1,3,5]])
print(a)
b = torch.tensor([[6,7], [8,9],[10,11]])
print(b)

tensor([[0, 2, 4],
        [1, 3, 5]])
tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])


In [116]:
# mm = matrix mult
# could also use @ but don't... 
print(torch.mm(a,b))
print(a @ b)

tensor([[56, 62],
        [80, 89]])
tensor([[56, 62],
        [80, 89]])


In [118]:
# euclidian norm
x = torch.tensor([2.,3.,4.,5.])
x.norm()

tensor(7.3485)

In [122]:
# number of elements
print(x.numel())
# or 
len(x)

4


4

In [123]:
# however for 2+d arrays, numel is better
a = torch.tensor([[0,2,4], [1,3,5]])
print(a.numel())
# or 
len(a)

6


2